[package]
name = "health-check-bot"
version = "0.1.0"
authors = ["Aiden McClelland <me@drbonez.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.4.0"
rand = "0.8.4"
ruma = { version = "0.2.0", features = ["api", "client-api", "appservice-api"] }
reqwest = { version = "0.11.4", features = ["blocking"] }
openssl = { version = "0.10.35", features = ["vendored"] }
serde = { version = "1.0.127", features = ["derive"] }
serde_yaml = "0.8.17"
